'use client'
import './global.css';
import './styles/style.scss';

import { Provider } from "react-redux";
import { store } from './reducers/store';
import { ApolloProvider, InMemoryCache, ApolloClient } from '@apollo/client';
import { usePathname } from 'next/navigation';
import { ROUTE } from './constants/route.constant';
import { Layout } from './component/layout/layout';

// import App from './app/app';
// import {persistor, store} from './reducers/store';



const client = new ApolloClient({
  cache: new InMemoryCache(),
  uri: `${process.env.SERVER_URL}graphql` //'http://localhost:3000/graphql',
});


// const metadata = {
//   title: 'Welcome to client',
//   description: 'Generated by create-nx-workspace',
// };

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  const pathName = usePathname()

  return (
    <html lang="en">
      <body>
      <ApolloProvider client={client}>
        <Provider store={store}>
            { (pathName.includes(ROUTE.LOGIN) || pathName.includes(ROUTE.SIGNUP) || pathName.includes(ROUTE.VIEWER)) ? 
              children : 
              <Layout>
                {children}
              </Layout>
            }
        </Provider>
        </ApolloProvider>
        {/* <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}> */}
          {/* </PersistGate>
        </Provider> */}
      </body>
    </html>
  );
}
